// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: xarex.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	XarexService_Register_FullMethodName   = "/xarex.XarexService/Register"
	XarexService_Heartbeat_FullMethodName  = "/xarex.XarexService/Heartbeat"
	XarexService_ScanStream_FullMethodName = "/xarex.XarexService/ScanStream"
)

// XarexServiceClient is the client API for XarexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XarexServiceClient interface {
	// Probe registers itself on startup
	Register(ctx context.Context, in *ProbeInfo, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Probe sends heartbeat every 30s, receives pending tasks
	Heartbeat(ctx context.Context, in *ProbeInfo, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Bidirectional stream: probe sends results, cloud sends tasks
	ScanStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ScanResult, ScanTask], error)
}

type xarexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewXarexServiceClient(cc grpc.ClientConnInterface) XarexServiceClient {
	return &xarexServiceClient{cc}
}

func (c *xarexServiceClient) Register(ctx context.Context, in *ProbeInfo, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, XarexService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xarexServiceClient) Heartbeat(ctx context.Context, in *ProbeInfo, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, XarexService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xarexServiceClient) ScanStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ScanResult, ScanTask], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &XarexService_ServiceDesc.Streams[0], XarexService_ScanStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanResult, ScanTask]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XarexService_ScanStreamClient = grpc.BidiStreamingClient[ScanResult, ScanTask]

// XarexServiceServer is the server API for XarexService service.
// All implementations must embed UnimplementedXarexServiceServer
// for forward compatibility.
type XarexServiceServer interface {
	// Probe registers itself on startup
	Register(context.Context, *ProbeInfo) (*HeartbeatResponse, error)
	// Probe sends heartbeat every 30s, receives pending tasks
	Heartbeat(context.Context, *ProbeInfo) (*HeartbeatResponse, error)
	// Bidirectional stream: probe sends results, cloud sends tasks
	ScanStream(grpc.BidiStreamingServer[ScanResult, ScanTask]) error
	mustEmbedUnimplementedXarexServiceServer()
}

// UnimplementedXarexServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedXarexServiceServer struct{}

func (UnimplementedXarexServiceServer) Register(context.Context, *ProbeInfo) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedXarexServiceServer) Heartbeat(context.Context, *ProbeInfo) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedXarexServiceServer) ScanStream(grpc.BidiStreamingServer[ScanResult, ScanTask]) error {
	return status.Errorf(codes.Unimplemented, "method ScanStream not implemented")
}
func (UnimplementedXarexServiceServer) mustEmbedUnimplementedXarexServiceServer() {}
func (UnimplementedXarexServiceServer) testEmbeddedByValue()                      {}

// UnsafeXarexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XarexServiceServer will
// result in compilation errors.
type UnsafeXarexServiceServer interface {
	mustEmbedUnimplementedXarexServiceServer()
}

func RegisterXarexServiceServer(s grpc.ServiceRegistrar, srv XarexServiceServer) {
	// If the following call pancis, it indicates UnimplementedXarexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&XarexService_ServiceDesc, srv)
}

func _XarexService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XarexServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XarexService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XarexServiceServer).Register(ctx, req.(*ProbeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _XarexService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XarexServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XarexService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XarexServiceServer).Heartbeat(ctx, req.(*ProbeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _XarexService_ScanStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(XarexServiceServer).ScanStream(&grpc.GenericServerStream[ScanResult, ScanTask]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XarexService_ScanStreamServer = grpc.BidiStreamingServer[ScanResult, ScanTask]

// XarexService_ServiceDesc is the grpc.ServiceDesc for XarexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XarexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xarex.XarexService",
	HandlerType: (*XarexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _XarexService_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _XarexService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ScanStream",
			Handler:       _XarexService_ScanStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "xarex.proto",
}
