// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.4
// source: xarex.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanTask_TaskType int32

const (
	ScanTask_HOST_DISCOVERY        ScanTask_TaskType = 0
	ScanTask_PORT_SCAN             ScanTask_TaskType = 1
	ScanTask_SERVICE_FINGERPRINT   ScanTask_TaskType = 2
	ScanTask_VULN_CHECK            ScanTask_TaskType = 3
	ScanTask_DEFAULT_CRED_TEST     ScanTask_TaskType = 4
	ScanTask_SMB_RELAY_CHECK       ScanTask_TaskType = 5
	ScanTask_LLMNR_POISON_CHECK    ScanTask_TaskType = 6
	ScanTask_KERBEROAST_ENUM       ScanTask_TaskType = 7
	ScanTask_ACTIVE_DIRECTORY_ENUM ScanTask_TaskType = 8
	ScanTask_CUSTOM                ScanTask_TaskType = 9
	ScanTask_SSL_TLS_AUDIT         ScanTask_TaskType = 10
	ScanTask_HTTP_SECURITY_HEADERS ScanTask_TaskType = 11
	ScanTask_DNS_ZONE_TRANSFER     ScanTask_TaskType = 12
	ScanTask_EXPOSED_ADMIN_PANEL   ScanTask_TaskType = 13
	ScanTask_SNMP_COMMUNITY_STRING ScanTask_TaskType = 14
	ScanTask_RDP_SECURITY_CHECK    ScanTask_TaskType = 15
	ScanTask_WEB_APP_SCAN          ScanTask_TaskType = 16
	ScanTask_NUCLEI_SCAN           ScanTask_TaskType = 17
)

// Enum value maps for ScanTask_TaskType.
var (
	ScanTask_TaskType_name = map[int32]string{
		0:  "HOST_DISCOVERY",
		1:  "PORT_SCAN",
		2:  "SERVICE_FINGERPRINT",
		3:  "VULN_CHECK",
		4:  "DEFAULT_CRED_TEST",
		5:  "SMB_RELAY_CHECK",
		6:  "LLMNR_POISON_CHECK",
		7:  "KERBEROAST_ENUM",
		8:  "ACTIVE_DIRECTORY_ENUM",
		9:  "CUSTOM",
		10: "SSL_TLS_AUDIT",
		11: "HTTP_SECURITY_HEADERS",
		12: "DNS_ZONE_TRANSFER",
		13: "EXPOSED_ADMIN_PANEL",
		14: "SNMP_COMMUNITY_STRING",
		15: "RDP_SECURITY_CHECK",
		16: "WEB_APP_SCAN",
		17: "NUCLEI_SCAN",
	}
	ScanTask_TaskType_value = map[string]int32{
		"HOST_DISCOVERY":        0,
		"PORT_SCAN":             1,
		"SERVICE_FINGERPRINT":   2,
		"VULN_CHECK":            3,
		"DEFAULT_CRED_TEST":     4,
		"SMB_RELAY_CHECK":       5,
		"LLMNR_POISON_CHECK":    6,
		"KERBEROAST_ENUM":       7,
		"ACTIVE_DIRECTORY_ENUM": 8,
		"CUSTOM":                9,
		"SSL_TLS_AUDIT":         10,
		"HTTP_SECURITY_HEADERS": 11,
		"DNS_ZONE_TRANSFER":     12,
		"EXPOSED_ADMIN_PANEL":   13,
		"SNMP_COMMUNITY_STRING": 14,
		"RDP_SECURITY_CHECK":    15,
		"WEB_APP_SCAN":          16,
		"NUCLEI_SCAN":           17,
	}
)

func (x ScanTask_TaskType) Enum() *ScanTask_TaskType {
	p := new(ScanTask_TaskType)
	*p = x
	return p
}

func (x ScanTask_TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScanTask_TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_xarex_proto_enumTypes[0].Descriptor()
}

func (ScanTask_TaskType) Type() protoreflect.EnumType {
	return &file_xarex_proto_enumTypes[0]
}

func (x ScanTask_TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScanTask_TaskType.Descriptor instead.
func (ScanTask_TaskType) EnumDescriptor() ([]byte, []int) {
	return file_xarex_proto_rawDescGZIP(), []int{3, 0}
}

type Finding_Severity int32

const (
	Finding_INFO     Finding_Severity = 0
	Finding_LOW      Finding_Severity = 1
	Finding_MEDIUM   Finding_Severity = 2
	Finding_HIGH     Finding_Severity = 3
	Finding_CRITICAL Finding_Severity = 4
)

// Enum value maps for Finding_Severity.
var (
	Finding_Severity_name = map[int32]string{
		0: "INFO",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	Finding_Severity_value = map[string]int32{
		"INFO":     0,
		"LOW":      1,
		"MEDIUM":   2,
		"HIGH":     3,
		"CRITICAL": 4,
	}
)

func (x Finding_Severity) Enum() *Finding_Severity {
	p := new(Finding_Severity)
	*p = x
	return p
}

func (x Finding_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Finding_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_xarex_proto_enumTypes[1].Descriptor()
}

func (Finding_Severity) Type() protoreflect.EnumType {
	return &file_xarex_proto_enumTypes[1]
}

func (x Finding_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Finding_Severity.Descriptor instead.
func (Finding_Severity) EnumDescriptor() ([]byte, []int) {
	return file_xarex_proto_rawDescGZIP(), []int{4, 0}
}

type ScanEvent_EventType int32

const (
	ScanEvent_PROBE_CONNECTED    ScanEvent_EventType = 0
	ScanEvent_TASK_STARTED       ScanEvent_EventType = 1
	ScanEvent_TASK_COMPLETED     ScanEvent_EventType = 2
	ScanEvent_FINDING_DISCOVERED ScanEvent_EventType = 3
	ScanEvent_ATTACK_PATH_BUILT  ScanEvent_EventType = 4
	ScanEvent_SCAN_COMPLETED     ScanEvent_EventType = 5
	ScanEvent_ERROR              ScanEvent_EventType = 6
)

// Enum value maps for ScanEvent_EventType.
var (
	ScanEvent_EventType_name = map[int32]string{
		0: "PROBE_CONNECTED",
		1: "TASK_STARTED",
		2: "TASK_COMPLETED",
		3: "FINDING_DISCOVERED",
		4: "ATTACK_PATH_BUILT",
		5: "SCAN_COMPLETED",
		6: "ERROR",
	}
	ScanEvent_EventType_value = map[string]int32{
		"PROBE_CONNECTED":    0,
		"TASK_STARTED":       1,
		"TASK_COMPLETED":     2,
		"FINDING_DISCOVERED": 3,
		"ATTACK_PATH_BUILT":  4,
		"SCAN_COMPLETED":     5,
		"ERROR":              6,
	}
)

func (x ScanEvent_EventType) Enum() *ScanEvent_EventType {
	p := new(ScanEvent_EventType)
	*p = x
	return p
}

func (x ScanEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScanEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_xarex_proto_enumTypes[2].Descriptor()
}

func (ScanEvent_EventType) Type() protoreflect.EnumType {
	return &file_xarex_proto_enumTypes[2]
}

func (x ScanEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScanEvent_EventType.Descriptor instead.
func (ScanEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_xarex_proto_rawDescGZIP(), []int{10, 0}
}

type ProbeInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProbeId        string                 `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	OrgId          string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities   []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	NetworkContext *NetworkContext        `protobuf:"bytes,5,opt,name=network_context,json=networkContext,proto3" json:"network_context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProbeInfo) Reset() {
	*x = ProbeInfo{}
	mi := &file_xarex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeInfo) ProtoMessage() {}

func (x *ProbeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_xarex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeInfo.ProtoReflect.Descriptor instead.
func (*ProbeInfo) Descriptor() ([]byte, []int) {
	return file_xarex_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeInfo) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ProbeInfo) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ProbeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProbeInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ProbeInfo) GetNetworkContext() *NetworkContext {
	if x != nil {
		return x.NetworkContext
	}
	return nil
}

type NetworkContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subnets       []string               `protobuf:"bytes,1,rep,name=subnets,proto3" json:"subnets,omitempty"`
	Gateways      []string               `protobuf:"bytes,2,rep,name=gateways,proto3" json:"gateways,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkContext) Reset() {
	*x = NetworkContext{}
	mi := &file_xarex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkContext) ProtoMessage() {}

func (x *NetworkContext) ProtoReflect() protoreflect.Message {
	mi := &file_xarex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkContext.ProtoReflect.Descriptor instead.
func (*NetworkContext) Descriptor() ([]byte, []int) {
	return file_xarex_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkContext) GetSubnets() []string {
	if x != nil {
		return x.Subnets
	}
	return nil
}

func (x *NetworkContext) GetGateways() []string {
	if x != nil {
		return x.Gateways
	}
	return nil
}

func (x *NetworkContext) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NetworkContext) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	PendingTasks  []*ScanTask            `protobuf:"bytes,2,rep,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_xarex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xarex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_xarex_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetPendingTasks() []*ScanTask {
	if x != nil {
		return x.PendingTasks
	}
	return nil
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ScanTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ScanId         string                 `protobuf:"bytes,2,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Type           ScanTask_TaskType      `protobuf:"varint,3,opt,name=type,proto3,enum=xarex.ScanTask_TaskType" json:"type,omitempty"`
	Params         map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScanTask) Reset() {
	*x = ScanTask{}
	mi := &file_xarex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanTask) ProtoMessage() {}

func (x *ScanTask) ProtoReflect() protoreflect.Message {
	mi := &file_xarex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanTask.ProtoReflect.Descriptor instead.
func (*ScanTask) Descriptor() ([]byte, []int) {
	return file_xarex_proto_rawDescGZIP(), []int{3}
}

func (x *ScanTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ScanTask) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanTask) GetType() ScanTask_TaskType {
	if x != nil {
		return x.Type
	}
	return ScanTask_HOST_DISCOVERY
}

func (x *ScanTask) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ScanTask) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FindingId     string                 `protobuf:"bytes,1,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ScanId        string                 `protobuf:"bytes,3,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Service       string                 `protobuf:"bytes,7,opt,name=service,proto3" json:"service,omitempty"`
	Severity      Finding_Severity       `protobuf:"varint,8,opt,name=severity,proto3,enum=xarex.Finding_Severity" json:"severity,omitempty"`
	CveId         string                 `protobuf:"bytes,9,opt,name=cve_id,json=cveId,proto3" json:"cve_id,omitempty"`
	Title         string                 `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	Evidence      string                 `protobuf:"bytes,12,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Remediation   string                 `protobuf:"bytes,13,opt,name=remediation,proto3" json:"remediation,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,14,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,15,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_xarex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_xarex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_xarex_proto_rawDescGZIP(), []int{4}
}

func (x *Finding) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

func (x *Finding) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Finding) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *Finding) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Finding) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Finding) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Finding) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Finding) GetSeverity() Finding_Severity {
	if x != nil {
		return x.Severity
	}
	return Finding_INFO
}

func (x *Finding) GetCveId() string {
	if x != nil {
		return x.CveId
	}
	return ""
}

func (x *Finding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Finding) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Finding) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *Finding) GetRemediation() string {
	if x != nil {
		return x.Remediation
	}
	return ""
}

func (x *Finding) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Finding) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ScanId        string                 `protobuf:"bytes,2,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	ProbeId       string                 `protobuf:"bytes,3,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Findings      []*Finding             `protobuf:"bytes,6,rep,name=findings,proto3" json:"findings,omitempty"`
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResult) Reset() {
	*x = ScanResult{}
	mi := &file_xarex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResult) ProtoMessage() {}

func (x *ScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_xarex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResult.ProtoReflect.Descriptor instead.
func (*ScanResult) Descriptor() ([]byte, []int) {
	return file_xarex_proto_rawDescGZIP(), []int{5}
}

func (x *ScanResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ScanResult) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanResult) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ScanResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScanResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ScanResult) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *ScanResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ScanResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	MacAddress    string                 `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	OsGuess       string                 `protobuf:"bytes,4,opt,name=os_guess,json=osGuess,proto3" json:"os_guess,omitempty"`
	OpenPorts     []*Port                `protobuf:"bytes,5,rep,name=open_ports,json=openPorts,proto3" json:"open_ports,omitempty"`
	IsAlive       bool                   `protobuf:"varint,6,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_xarex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_xarex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_xarex_proto_rawDescGZIP(), []int{6}
}

func (x *Host) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Host) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Host) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *Host) GetOsGuess() string {
	if x != nil {
		return x.OsGuess
	}
	return ""
}

func (x *Host) GetOpenPorts() []*Port {
	if x != nil {
		return x.OpenPorts
	}
	return nil
}

func (x *Host) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

type Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // tcp/udp
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`       // open/filtered/closed
	Service       string                 `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Banner        string                 `protobuf:"bytes,5,opt,name=banner,proto3" json:"banner,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_xarex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_xarex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_xarex_proto_rawDescGZIP(), []int{7}
}

func (x *Port) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Port) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Port) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Port) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Port) GetBanner() string {
	if x != nil {
		return x.Banner
	}
	return ""
}

func (x *Port) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AttackPathNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	FindingId     string                 `protobuf:"bytes,2,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Technique     string                 `protobuf:"bytes,4,opt,name=technique,proto3" json:"technique,omitempty"` // MITRE ATT&CK technique ID
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	NextNodeIds   []string               `protobuf:"bytes,6,rep,name=next_node_ids,json=nextNodeIds,proto3" json:"next_node_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackPathNode) Reset() {
	*x = AttackPathNode{}
	mi := &file_xarex_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackPathNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackPathNode) ProtoMessage() {}

func (x *AttackPathNode) ProtoReflect() protoreflect.Message {
	mi := &file_xarex_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackPathNode.ProtoReflect.Descriptor instead.
func (*AttackPathNode) Descriptor() ([]byte, []int) {
	return file_xarex_proto_rawDescGZIP(), []int{8}
}

func (x *AttackPathNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AttackPathNode) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

func (x *AttackPathNode) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AttackPathNode) GetTechnique() string {
	if x != nil {
		return x.Technique
	}
	return ""
}

func (x *AttackPathNode) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AttackPathNode) GetNextNodeIds() []string {
	if x != nil {
		return x.NextNodeIds
	}
	return nil
}

type AttackPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathId        string                 `protobuf:"bytes,1,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	ScanId        string                 `protobuf:"bytes,2,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Nodes         []*AttackPathNode      `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	RiskScore     float32                `protobuf:"fixed32,4,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Impact        string                 `protobuf:"bytes,5,opt,name=impact,proto3" json:"impact,omitempty"`
	EntryPoint    string                 `protobuf:"bytes,6,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	Target        string                 `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackPath) Reset() {
	*x = AttackPath{}
	mi := &file_xarex_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackPath) ProtoMessage() {}

func (x *AttackPath) ProtoReflect() protoreflect.Message {
	mi := &file_xarex_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackPath.ProtoReflect.Descriptor instead.
func (*AttackPath) Descriptor() ([]byte, []int) {
	return file_xarex_proto_rawDescGZIP(), []int{9}
}

func (x *AttackPath) GetPathId() string {
	if x != nil {
		return x.PathId
	}
	return ""
}

func (x *AttackPath) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *AttackPath) GetNodes() []*AttackPathNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *AttackPath) GetRiskScore() float32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *AttackPath) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

func (x *AttackPath) GetEntryPoint() string {
	if x != nil {
		return x.EntryPoint
	}
	return ""
}

func (x *AttackPath) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type ScanEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Type          ScanEvent_EventType    `protobuf:"varint,2,opt,name=type,proto3,enum=xarex.ScanEvent_EventType" json:"type,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanEvent) Reset() {
	*x = ScanEvent{}
	mi := &file_xarex_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanEvent) ProtoMessage() {}

func (x *ScanEvent) ProtoReflect() protoreflect.Message {
	mi := &file_xarex_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanEvent.ProtoReflect.Descriptor instead.
func (*ScanEvent) Descriptor() ([]byte, []int) {
	return file_xarex_proto_rawDescGZIP(), []int{10}
}

func (x *ScanEvent) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanEvent) GetType() ScanEvent_EventType {
	if x != nil {
		return x.Type
	}
	return ScanEvent_PROBE_CONNECTED
}

func (x *ScanEvent) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *ScanEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_xarex_proto protoreflect.FileDescriptor

const file_xarex_proto_rawDesc = "" +
	"\n" +
	"\vxarex.proto\x12\x05xarex\"\xbb\x01\n" +
	"\tProbeInfo\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\tR\aprobeId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12>\n" +
	"\x0fnetwork_context\x18\x05 \x01(\v2\x15.xarex.NetworkContextR\x0enetworkContext\"r\n" +
	"\x0eNetworkContext\x12\x18\n" +
	"\asubnets\x18\x01 \x03(\tR\asubnets\x12\x1a\n" +
	"\bgateways\x18\x02 \x03(\tR\bgateways\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\"\x87\x01\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x124\n" +
	"\rpending_tasks\x18\x02 \x03(\v2\x0f.xarex.ScanTaskR\fpendingTasks\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x90\x05\n" +
	"\bScanTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\ascan_id\x18\x02 \x01(\tR\x06scanId\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.xarex.ScanTask.TaskTypeR\x04type\x123\n" +
	"\x06params\x18\x04 \x03(\v2\x1b.xarex.ScanTask.ParamsEntryR\x06params\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x03\n" +
	"\bTaskType\x12\x12\n" +
	"\x0eHOST_DISCOVERY\x10\x00\x12\r\n" +
	"\tPORT_SCAN\x10\x01\x12\x17\n" +
	"\x13SERVICE_FINGERPRINT\x10\x02\x12\x0e\n" +
	"\n" +
	"VULN_CHECK\x10\x03\x12\x15\n" +
	"\x11DEFAULT_CRED_TEST\x10\x04\x12\x13\n" +
	"\x0fSMB_RELAY_CHECK\x10\x05\x12\x16\n" +
	"\x12LLMNR_POISON_CHECK\x10\x06\x12\x13\n" +
	"\x0fKERBEROAST_ENUM\x10\a\x12\x19\n" +
	"\x15ACTIVE_DIRECTORY_ENUM\x10\b\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\t\x12\x11\n" +
	"\rSSL_TLS_AUDIT\x10\n" +
	"\x12\x19\n" +
	"\x15HTTP_SECURITY_HEADERS\x10\v\x12\x15\n" +
	"\x11DNS_ZONE_TRANSFER\x10\f\x12\x17\n" +
	"\x13EXPOSED_ADMIN_PANEL\x10\r\x12\x19\n" +
	"\x15SNMP_COMMUNITY_STRING\x10\x0e\x12\x16\n" +
	"\x12RDP_SECURITY_CHECK\x10\x0f\x12\x10\n" +
	"\fWEB_APP_SCAN\x10\x10\x12\x0f\n" +
	"\vNUCLEI_SCAN\x10\x11\"\xd2\x04\n" +
	"\aFinding\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x01 \x01(\tR\tfindingId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x17\n" +
	"\ascan_id\x18\x03 \x01(\tR\x06scanId\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x18\n" +
	"\aservice\x18\a \x01(\tR\aservice\x123\n" +
	"\bseverity\x18\b \x01(\x0e2\x17.xarex.Finding.SeverityR\bseverity\x12\x15\n" +
	"\x06cve_id\x18\t \x01(\tR\x05cveId\x12\x14\n" +
	"\x05title\x18\n" +
	" \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12\x1a\n" +
	"\bevidence\x18\f \x01(\tR\bevidence\x12 \n" +
	"\vremediation\x18\r \x01(\tR\vremediation\x128\n" +
	"\bmetadata\x18\x0e \x03(\v2\x1c.xarex.Finding.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\x0f \x01(\x03R\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\bSeverity\x12\b\n" +
	"\x04INFO\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x04\"\xf4\x01\n" +
	"\n" +
	"ScanResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\ascan_id\x18\x02 \x01(\tR\x06scanId\x12\x19\n" +
	"\bprobe_id\x18\x03 \x01(\tR\aprobeId\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12*\n" +
	"\bfindings\x18\x06 \x03(\v2\x0e.xarex.FindingR\bfindings\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"\xb5\x01\n" +
	"\x04Host\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\x12\x19\n" +
	"\bos_guess\x18\x04 \x01(\tR\aosGuess\x12*\n" +
	"\n" +
	"open_ports\x18\x05 \x03(\v2\v.xarex.PortR\topenPorts\x12\x19\n" +
	"\bis_alive\x18\x06 \x01(\bR\aisAlive\"\x9c\x01\n" +
	"\x04Port\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x16\n" +
	"\x06banner\x18\x05 \x01(\tR\x06banner\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"\xc0\x01\n" +
	"\x0eAttackPathNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x02 \x01(\tR\tfindingId\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x1c\n" +
	"\ttechnique\x18\x04 \x01(\tR\ttechnique\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\"\n" +
	"\rnext_node_ids\x18\x06 \x03(\tR\vnextNodeIds\"\xdb\x01\n" +
	"\n" +
	"AttackPath\x12\x17\n" +
	"\apath_id\x18\x01 \x01(\tR\x06pathId\x12\x17\n" +
	"\ascan_id\x18\x02 \x01(\tR\x06scanId\x12+\n" +
	"\x05nodes\x18\x03 \x03(\v2\x15.xarex.AttackPathNodeR\x05nodes\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x04 \x01(\x02R\triskScore\x12\x16\n" +
	"\x06impact\x18\x05 \x01(\tR\x06impact\x12\x1f\n" +
	"\ventry_point\x18\x06 \x01(\tR\n" +
	"entryPoint\x12\x16\n" +
	"\x06target\x18\a \x01(\tR\x06target\"\xac\x02\n" +
	"\tScanEvent\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.xarex.ScanEvent.EventTypeR\x04type\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x94\x01\n" +
	"\tEventType\x12\x13\n" +
	"\x0fPROBE_CONNECTED\x10\x00\x12\x10\n" +
	"\fTASK_STARTED\x10\x01\x12\x12\n" +
	"\x0eTASK_COMPLETED\x10\x02\x12\x16\n" +
	"\x12FINDING_DISCOVERED\x10\x03\x12\x15\n" +
	"\x11ATTACK_PATH_BUILT\x10\x04\x12\x12\n" +
	"\x0eSCAN_COMPLETED\x10\x05\x12\t\n" +
	"\x05ERROR\x10\x062\xb5\x01\n" +
	"\fXarexService\x126\n" +
	"\bRegister\x12\x10.xarex.ProbeInfo\x1a\x18.xarex.HeartbeatResponse\x127\n" +
	"\tHeartbeat\x12\x10.xarex.ProbeInfo\x1a\x18.xarex.HeartbeatResponse\x124\n" +
	"\n" +
	"ScanStream\x12\x11.xarex.ScanResult\x1a\x0f.xarex.ScanTask(\x010\x01B Z\x1egithub.com/xarex/probe/grpc/pbb\x06proto3"

var (
	file_xarex_proto_rawDescOnce sync.Once
	file_xarex_proto_rawDescData []byte
)

func file_xarex_proto_rawDescGZIP() []byte {
	file_xarex_proto_rawDescOnce.Do(func() {
		file_xarex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xarex_proto_rawDesc), len(file_xarex_proto_rawDesc)))
	})
	return file_xarex_proto_rawDescData
}

var file_xarex_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_xarex_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_xarex_proto_goTypes = []any{
	(ScanTask_TaskType)(0),    // 0: xarex.ScanTask.TaskType
	(Finding_Severity)(0),     // 1: xarex.Finding.Severity
	(ScanEvent_EventType)(0),  // 2: xarex.ScanEvent.EventType
	(*ProbeInfo)(nil),         // 3: xarex.ProbeInfo
	(*NetworkContext)(nil),    // 4: xarex.NetworkContext
	(*HeartbeatResponse)(nil), // 5: xarex.HeartbeatResponse
	(*ScanTask)(nil),          // 6: xarex.ScanTask
	(*Finding)(nil),           // 7: xarex.Finding
	(*ScanResult)(nil),        // 8: xarex.ScanResult
	(*Host)(nil),              // 9: xarex.Host
	(*Port)(nil),              // 10: xarex.Port
	(*AttackPathNode)(nil),    // 11: xarex.AttackPathNode
	(*AttackPath)(nil),        // 12: xarex.AttackPath
	(*ScanEvent)(nil),         // 13: xarex.ScanEvent
	nil,                       // 14: xarex.ScanTask.ParamsEntry
	nil,                       // 15: xarex.Finding.MetadataEntry
}
var file_xarex_proto_depIdxs = []int32{
	4,  // 0: xarex.ProbeInfo.network_context:type_name -> xarex.NetworkContext
	6,  // 1: xarex.HeartbeatResponse.pending_tasks:type_name -> xarex.ScanTask
	0,  // 2: xarex.ScanTask.type:type_name -> xarex.ScanTask.TaskType
	14, // 3: xarex.ScanTask.params:type_name -> xarex.ScanTask.ParamsEntry
	1,  // 4: xarex.Finding.severity:type_name -> xarex.Finding.Severity
	15, // 5: xarex.Finding.metadata:type_name -> xarex.Finding.MetadataEntry
	7,  // 6: xarex.ScanResult.findings:type_name -> xarex.Finding
	10, // 7: xarex.Host.open_ports:type_name -> xarex.Port
	11, // 8: xarex.AttackPath.nodes:type_name -> xarex.AttackPathNode
	2,  // 9: xarex.ScanEvent.type:type_name -> xarex.ScanEvent.EventType
	3,  // 10: xarex.XarexService.Register:input_type -> xarex.ProbeInfo
	3,  // 11: xarex.XarexService.Heartbeat:input_type -> xarex.ProbeInfo
	8,  // 12: xarex.XarexService.ScanStream:input_type -> xarex.ScanResult
	5,  // 13: xarex.XarexService.Register:output_type -> xarex.HeartbeatResponse
	5,  // 14: xarex.XarexService.Heartbeat:output_type -> xarex.HeartbeatResponse
	6,  // 15: xarex.XarexService.ScanStream:output_type -> xarex.ScanTask
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_xarex_proto_init() }
func file_xarex_proto_init() {
	if File_xarex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xarex_proto_rawDesc), len(file_xarex_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xarex_proto_goTypes,
		DependencyIndexes: file_xarex_proto_depIdxs,
		EnumInfos:         file_xarex_proto_enumTypes,
		MessageInfos:      file_xarex_proto_msgTypes,
	}.Build()
	File_xarex_proto = out.File
	file_xarex_proto_goTypes = nil
	file_xarex_proto_depIdxs = nil
}
