# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import xarex_pb2 as xarex__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in xarex_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class XarexServiceStub(object):
    """─────────────────────────────────────────────
    gRPC Service Definition
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/xarex.XarexService/Register',
                request_serializer=xarex__pb2.ProbeInfo.SerializeToString,
                response_deserializer=xarex__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/xarex.XarexService/Heartbeat',
                request_serializer=xarex__pb2.ProbeInfo.SerializeToString,
                response_deserializer=xarex__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ScanStream = channel.stream_stream(
                '/xarex.XarexService/ScanStream',
                request_serializer=xarex__pb2.ScanResult.SerializeToString,
                response_deserializer=xarex__pb2.ScanTask.FromString,
                _registered_method=True)


class XarexServiceServicer(object):
    """─────────────────────────────────────────────
    gRPC Service Definition
    ─────────────────────────────────────────────

    """

    def Register(self, request, context):
        """Probe registers itself on startup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Probe sends heartbeat every 30s, receives pending tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanStream(self, request_iterator, context):
        """Bidirectional stream: probe sends results, cloud sends tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XarexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=xarex__pb2.ProbeInfo.FromString,
                    response_serializer=xarex__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=xarex__pb2.ProbeInfo.FromString,
                    response_serializer=xarex__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ScanStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ScanStream,
                    request_deserializer=xarex__pb2.ScanResult.FromString,
                    response_serializer=xarex__pb2.ScanTask.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xarex.XarexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xarex.XarexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class XarexService(object):
    """─────────────────────────────────────────────
    gRPC Service Definition
    ─────────────────────────────────────────────

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xarex.XarexService/Register',
            xarex__pb2.ProbeInfo.SerializeToString,
            xarex__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xarex.XarexService/Heartbeat',
            xarex__pb2.ProbeInfo.SerializeToString,
            xarex__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/xarex.XarexService/ScanStream',
            xarex__pb2.ScanResult.SerializeToString,
            xarex__pb2.ScanTask.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
